---
format: gfm
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "How to Use Agentic AI for Responsible Archaeological Data Analysis"
```

# How to Use Agentic AI for Responsible Archaeological Data Analysis


This repository contains the data and code for our paper:

> Marwick, B. (submitted). _`r Title`_. Advances in Archaeological Practice <https://doi.org/xxx/xxx>

Our pre-print is online here:

> Marwick, B. (2026). _`r Title`_. Advances in Archaeological Practice Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/xxx/xxx>


### How to cite

Please cite this compendium as:

> Marwick, B. (`r format(Sys.Date(), "%Y")`). _Compendium for `r Title`_. Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/xxx/xxx>

## Contents

The **analysis** directory contains:

  - [:file\_folder: paper](/analysis/paper): Quarto source document
    for manuscript. Includes code to reproduce the figures and tables
    generated by the analysis. It also has a rendered version,
    `paper.docx`, suitable for reading (the code is replaced by figures
    and tables in this file)
  - [:file\_folder: data](/analysis/data): Data used in the analysis.
  - [:file\_folder: figures](/analysis/figures): Plots and other
    illustrations
  - [:file\_folder:
    supplementary-materials](/analysis/supplementary-materials):
    Supplementary materials including notes and other documents
    prepared and collected during the analysis.

### Licenses

**Text and figures :**  [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)

**Code :** See the [DESCRIPTION](DESCRIPTION) file

**Data :** [CC-0](http://creativecommons.org/publicdomain/zero/1.0/) attribution requested in reuse

### Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.md). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.

